### ISSUE TITLE
Zero connections to the account. 

### ISSUE THREAD

**Issue by Tafer181** [MsLolita/grass#100]
Zero connections to the account. The software says accounts are connected and mining, but the 'logs' folder always shows zero mining. The IP shows an average value of 75-100 mining in one day of usage, and everything was fine at first. However, later, the software reports that everything is connected, but it's not mining anything.

**Comment by Bekloppten** [comment]
i experience the same in the last days.
tried everything .... a few gigs of  different proxies. after that, i thought maybe my account is shadowbanned... so i used other accounts, old ones and brand new ones, i even setup another vps. please if somebody find a solution, please tell me :D

**Comment by MsLolita** [comment]
fixed 5days ago
