### ISSUE TITLE
майнит без майна 

### ISSUE THREAD

**Issue by Tafer181** [MsLolita/grass#102]
"Я подключил прокси к своему аккаунту, все аккаунты были видны и работали. На следующий день, запустив софт, я увидел 0 подключений, хотя в самом софте не было ошибок, и он показывал, что все майнится. Я подумал, что это проблема отображения в Grass, и что очки будут начислены на следующий день. Но нет, я продолжал фармить как обычно. Сколько бы раз я не перезапускал софт или менял параметры (MIN_Proxy_score на 0, 50, 75, 100), ничего не помогало. Прокси подходят для Grass, в антидетект браузере все майнится. Насколько я понял, параметры фарма в папке logs [32m18:21:13.38[0m [34mINFO[0m [1m7 | Mined grass.[0m . Однако майнинг типа идет, а время подключения показывает 0 минут. В чем проблема?"

**Comment by whxami** [comment]
+1

**Comment by BRN-SLP** [comment]
+

**Comment by FiNT222** [comment]
Скачал только что последнюю версию софта. Минт идёт в софте, но отображения в дашборде нет. В тоже время через расширение в браузере поинты начисляются и отображаются в дашборде.

**Comment by MsLolita** [comment]
как 4 дня назад пофиксил

**Comment by Tafer181** [comment]
проблема сново вернулась точно такаяже
