### ISSUE TITLE
Some new troubles

### ISSUE THREAD

**Issue by NadNotMad** [MsLolita/grass#107]
It seems grass has a new trouble? dashboard doesn't update the score and connected ip. 
<img width="614" alt="2024-12-18 015310" src="https://github.com/user-attachments/assets/baf8c5d2-4562-4bc8-9ca2-8d432223f173" />

**Comment by rizexin** [comment]
me too

**Comment by ikkan08** [comment]
me too

**Comment by Jhinkz018** [comment]
i got similar, and want to ask which protocol or format to be use haha

**Comment by yuanl00** [comment]
+1

**Comment by yuanl00** [comment]
message type is: '{"id":"iK_b07ky-wXEKUWdZl9QK","action":"OPEN_TUNNEL","data":{"url":"https://api.getgrass.io/e65c798e44045cf3241e5bdc52aff12c/035pUCF8ZNaRAG2P"}}'

client not 'HTTP_REQUEST'

**Comment by tructhienbui** [comment]
> message type is: '{"id":"iK_b07ky-wXEKUWdZl9QK","action":"OPEN_TUNNEL","data":{"url":"[https://api.getgrass.io/e65c798e44045cf3241e5bdc52aff12c/035pUCF8ZNaRAG2P"}}](https://api.getgrass.io/e65c798e44045cf3241e5bdc52aff12c/035pUCF8ZNaRAG2P%22%7D%7D)'
> 
> desktop not 'HTTP_REQUEST'

Yeah seem like theyhave just make change from HTTP_REQUEST to new action called OPEN_TUNNEL, see and discuss more at #108 .
