### ISSUE TITLE
Is anyone able to use the system normally?  My system is not running and is sucking up all my GB from the proxy

### ISSUE THREAD

**Issue by ikkan08** [MsLolita/grass#116]

**Comment by MsLolita** [comment]
use 1.25x, it works good

**Comment by ikkan08** [comment]
> use 1.25x, it works good

![explorer_ipHFnTlDkl](https://github.com/user-attachments/assets/9398e3c2-1af7-48e5-9e3e-df2188c83069)


not conected, only score not found. 
if I turned Score  Check to 0, the mine is only visual and not reflected to dashboard
