### ISSUE TITLE
Epoch 4 error

### ISSUE THREAD

**Issue by Estereg** [MsLolita/grass#12]
Since I started epoch 4 it won't let me connect my accounts, it only shows connecting and then throws errors. For proxy I am using proxy-seller 
![image](https://github.com/MsLolita/grass/assets/109712545/e4e14d1e-c39b-4a91-ad23-3a26ab543cfe)

**Comment by MsLolita** [comment]
Soft is working correctly, if connecting didn't work simply change proxy provider. Nowadays many proxy services (like proxy-seller, froxy, bee ...) are under ban from grass, even my real ip with wi-fi got there, so I tried a bunch of services and updated the list here https://teletype.in/@web3enjoyer/4a2G9NuHssy.
