### ISSUE TITLE
ask to change CLAIM_REWARDS_ONLY

### ISSUE THREAD

**Issue by smeshny** [MsLolita/grass#18]
Is it possible to make it so that the claiming of rewards happens randomly and while the script is running?

Because when you enable claiming of rewards, they all start to be claime in a row, which looks very suspicious!

**Comment by MsLolita** [comment]
Re-check pls, you can change amount of threads to start only one account by one

**Comment by smeshny** [comment]
Thank you for your reply
But I didn't mean the number of threads, but meant the possibility of random claiming during mining, to make it look less suspicious.

For example:
I have 100 accounts and want to set during the week accounts randomly claiming rewards.

But now I can claim only one by one. And during this process, I need to stop mining.
