### ISSUE TITLE
Grass Point Dropped

### ISSUE THREAD

**Issue by jokiindo** [MsLolita/grass#2]
when the script runs, the process runs smoothly and the grass points increase. but when the script is stopped the points decrease back to normal again. even though I have bought a static residential proxy. Maybe the system can be repaired. Thank You

**Comment by MsLolita** [comment]
yeap bro, there is this problem on grass.io, I'm not sure when they will fix it, but mostly on all accounts they refund points in the next day or some days. This error started a few days ago when a major update was made. It's the same problem in the browser, so I can't fix the bug on their servers.
