### ISSUE TITLE
Captcha issue

### ISSUE THREAD

**Issue by ilyacosmos** [MsLolita/grass#24]
Congratulations on the Easter holiday! I am facing a captcha problem when registering, how can I solve it?
---
 | not handled exception | error: Create acc response: | {"error":{"message":"reCAPTCHA verification failed.","code":-32600,"data":{"code":"BAD_REQUEST","httpStatus":400,"stack":"TRPCError: reCAPTCHA verification failed.\n    at /app/dist/index.js:2:1575537\n    at async Zf.Vf.middlewares (/app/dist/index.js:2:1106457)\n    at async n (/app/dist/index.js:2:1105869)","path":"register"}}} Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\grass-master\main.py", line 56, in worker_task
    await grass.create_account()
  File "C:\Users\Administrator\Desktop\grass-master\core\grass_sdk\website.py", line 57, in create_account
    raise aiohttp.ClientConnectionError(f"Create acc response: | {await response.text()}")
aiohttp.client_exceptions.ClientConnectionError: Create acc response: | {"error":{"message":"reCAPTCHA verification failed.","code":-32600,"data":{"code":"BAD_REQUEST","httpStatus":400,"stack":"TRPCError: reCAPTCHA verification failed.\n    at /app/dist/index.js:2:1575537\n    at async Zf.Vf.middlewares (/app/dist/index.js:2:1106457)\n    at async n (/app/dist/index.js:2:1105869)","path":"register"}}}

**Comment by MsLolita** [comment]
Hi, try another captcah solving service.
