### ISSUE TITLE
Unknown error found

### ISSUE THREAD

**Issue by shiwenbin1617** [MsLolita/grass#25]
The log shows that it is always connected, but there is no structure
![image](https://github.com/MsLolita/grass/assets/136685106/e25de60c-b5c9-4d8f-a27c-17ea219c769e)

**Comment by xeezh** [comment]
### Same error.

It appears at connect function. If you aren't using proxy it works normally.

The error is _502 Bad Gateway_
![image](https://github.com/MsLolita/grass/assets/67314424/7d6ecb95-30ca-4d19-9f48-1a64d18cc5b1)

Tried to:
- change headers
- change endpoint
- change proxy
- change proxy type for socks (BTW doesn't work at all)
- set ssl_verify=False
- this patch https://github.com/aio-libs/aiohttp/discussions/6044#discussioncomment-1432443

Nothing helps =(

By the way, if i set proxy globally on PC (for ex. by Proxifier), it works good.

**Comment by MsLolita** [comment]
You need to change your proxy provider. This error (only the words "Connecting...") means that the site has detected that you are using a proxy and has not connected you.
