### ISSUE TITLE
points are not counted

### ISSUE THREAD

**Issue by Faruk0n** [MsLolita/grass#30]
Why does the grass mine well during the day and reach the 2400 points (proxy scrore 100%), but when the day has passed, the next day these points are written off from me, and in the list of devices the mining time on IP has decreased. What could be the problem?
![Снимок экрана 2024-06-06 142829](https://github.com/MsLolita/grass/assets/69689953/77528808-93c4-4064-a350-6c409deeef2d)

**Comment by MsLolita** [comment]
Yes, it's normal, the grass servers are often down, and I think they just turn off the scoring, it's already season 6, and the scoring was so bad in season 2, so it's absolutely normal and everyone has it.
