### ISSUE TITLE
Error Module

### ISSUE THREAD

**Issue by adryan089** [MsLolita/grass#37]
Traceback (most recent call last):
  File "F:\CryptoCurrency Data\Bot\Grass\main.py", line 8, in <module>
    from core import Grass
  File "F:\CryptoCurrency Data\Bot\Grass\core\__init__.py", line 1, in <module>
    from .logger import logger
ModuleNotFoundError: No module named 'core.logger'

and I tried to install the module with pip install core.logger I found an error again

ERROR: Could not find a version that satisfies the requirement core.logger (from versions: none)
ERROR: No matching distribution found for core.logger

**Comment by MsLolita** [comment]
Hi, start soft from grass main folder and install all from requirements.txt
