### ISSUE TITLE
No score

### ISSUE THREAD

**Issue by maianhbao1** [MsLolita/grass#44]
run 30 minutes but no score

**Comment by pzdc-pixel** [comment]
You can change proxys and check again, but I seems such problem: after few hours of mining the new day in grass starts, and after it, my point been wiped (mined by local node and by script). I'm mines uses this script setup all proxys to one main account in grass. Does it make sense to do this, or should I create multiple accounts for protecting my mining results from wipe when calculating of drop?

**Comment by MsLolita** [comment]
try to skip checking of score by addding MIN_PROXY_SCORE = 0 to config.py
