### ISSUE TITLE
REFERAL

### ISSUE THREAD

**Issue by jokiindo** [MsLolita/grass#5]
where where can I put my referral code? I have tried auto register but the referrals are not counted in the main account

**Comment by Konders** [comment]
config.py -> REF_CODE

**Comment by MsLolita** [comment]
in config.py put in any line REF_CODE="your_code"
![image](https://github.com/MsLolita/grass/assets/58307006/abf6f2e4-bd8f-4c83-93f9-b283b3dd92ac)
