### ISSUE TITLE
Errors to fix

### ISSUE THREAD

**Issue by groovg** [MsLolita/grass#58]
After recent update(s) only more errors and problems occured. Now I'm constantly getting these types of errors: 
Type error: the JSON object must be str, bytes or bytearray, not int. Reconnecting...
Reconnecting with delay for some minutes...

Websocket closed: Websocket closed: WSMessage(type=<WSMsgType.CLOSED: 257>, data=None, extra=None). Reconnecting...

Using only gemups proxies. Please, fix these errors :)

**Comment by MsLolita** [comment]
grass servers issue
