### ISSUE TITLE
туториал

### ISSUE THREAD

**Issue by enfise** [MsLolita/grass#62]
А можете сделать видео туториал, пожалуйста

**Comment by Pon97** [comment]
Не выебывайся, так разбирайся :)

**Comment by enfise** [comment]
> Не выебывайся, так разбирайся :)

спасибо

**Comment by MsLolita** [comment]
> > Не выебывайся, так разбирайся :)
> 
> спасибо

та бля да хочу сделать только вот что то долго контент мейкер думет
