### ISSUE TITLE
Nice try to steal referrals! Well done guys!! 

### ISSUE THREAD

**Issue by Djang0-Unchained** [MsLolita/grass#70]
<img width="1060" alt="image" src="https://github.com/user-attachments/assets/4113805e-fbb0-45a8-95b0-abe6dfdc0df1">

**Comment by bringlive** [comment]
How to change it?

**Comment by Djang0-Unchained** [comment]
> How to change it?

This is how this method should look like:

```
    async def get_json_params(self, params, user_referral: str):
        self.username = Person().username

        json_data = {
            'email': self.email,
            'password': self.password,
            'role': 'USER',
            'referralCode': user_referral,
            'username': self.username,
            'recaptchaToken': "",
            'listIds': [
                15,
            ],
        }

        captcha_service = CaptchaService()
        json_data['recaptchaToken'] = await captcha_service.get_captcha_token_async()

        return json_data
```

**Comment by Djang0-Unchained** [comment]
> > How to change it?
> 
> This is how this method should look like:
> 
> ```
>     async def get_json_params(self, params, user_referral: str):
>         self.username = Person().username
> 
>         json_data = {
>             'email': self.email,
>             'password': self.password,
>             'role': 'USER',
>             'referralCode': user_referral,
>             'username': self.username,
>             'recaptchaToken': "",
>             'listIds': [
>                 15,
>             ],
>         }
> 
>         captcha_service = CaptchaService()
>         json_data['recaptchaToken'] = await captcha_service.get_captcha_token_async()
> 
>         return json_data
> ```
At least it won't transfer referrals to a third-party account. However, I still have one concern: the `listIds` variable. I'm not entirely sure what it means, and I suspect it could potentially be used maliciously. I'll look into it further.

**Comment by Djang0-Unchained** [comment]
> > > How to change it?
> > 
> > 
> > This is how this method should look like:
> > ```
> >     async def get_json_params(self, params, user_referral: str):
> >         self.username = Person().username
> > 
> >         json_data = {
> >             'email': self.email,
> >             'password': self.password,
> >             'role': 'USER',
> >             'referralCode': user_referral,
> >             'username': self.username,
> >             'recaptchaToken': "",
> >             'listIds': [
> >                 15,
> >             ],
> >         }
> > 
> >         captcha_service = CaptchaService()
> >         json_data['recaptchaToken'] = await captcha_service.get_captcha_token_async()
> > 
> >         return json_data
> > ```
> 
> At least it won't transfer referrals to a third-party account. However, I still have one concern: the `listIds` param. I'm not entirely sure what it means, and I suspect it could potentially be used maliciously. I'll look into it further.
I just checked the information regarding the listIds parameter, and there’s nothing malicious. The method I provided above is safe to use.

**Comment by Djang0-Unchained** [comment]
> > > How to change it?
> > 
> > 
> > This is how this method should look like:
> > ```
> >     async def get_json_params(self, params, user_referral: str):
> >         self.username = Person().username
> > 
> >         json_data = {
> >             'email': self.email,
> >             'password': self.password,
> >             'role': 'USER',
> >             'referralCode': user_referral,
> >             'username': self.username,
> >             'recaptchaToken': "",
> >             'listIds': [
> >                 15,
> >             ],
> >         }
> > 
> >         captcha_service = CaptchaService()
> >         json_data['recaptchaToken'] = await captcha_service.get_captcha_token_async()
> > 
> >         return json_data
> > ```
> 
> At least it won't transfer referrals to a third-party account. However, I still have one concern: the `listIds` param. I'm not entirely sure what it means, and I suspect it could potentially be used maliciously. I'll look into it further.

Just checked the info regarding  `listIds` param, and nothing malicious.
So the method above is good to use.

**Comment by MsLolita** [comment]
What's wrong with that? As I said in my telegram public, I only take 50% because it's my software, so you can create your own, of course.
