### ISSUE TITLE
Attempt to decode JSON with unexpected mimetype: text/html;

### ISSUE THREAD

**Issue by ezreal130** [MsLolita/grass#75]
01:14:30.12 INFO 3 | Login retrying... 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.getgrass.io/login')
01:14:30.32 INFO 5 | Login retrying... 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.getgrass.io/login')
01:14:31.30 INFO 1 | Login retrying... 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.getgrass.io/login')
01:14:31.34 INFO 7 | Login retrying... 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.getgrass.io/login')
01:14:31.35 INFO 14 | Login retrying... 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.getgrass.io/login')
01:14:31.66 INFO 23 | Login retrying... 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.getgrass.io/login')
01:14:31.96 INFO 8 | Login retrying... 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.getgrass.io/login')

**Comment by bulat-gab** [comment]
https://github.com/MsLolita/grass/pull/76 should fix it

**Comment by MsLolita** [comment]
I am not sure what is this.  #76 is already added but I am not sure that it can solve it
