### ISSUE TITLE
Sec-WebSocket-Key

### ISSUE THREAD

**Issue by tamved** [MsLolita/grass#82]
every connect 'Sec-WebSocket-Key' is uniq
mb replace 'Sec-WebSocket-Key': '94BKvjUp/+zImAvhNQWT3w==', with generated? 

    random_bytes = os.urandom(16)
    sec_websocket_key = base64.b64encode(random_bytes).decode('utf-8')

**Comment by MsLolita** [comment]
Okey, cool, thx
