### ISSUE TITLE
ERROR after update

### ISSUE THREAD

**Issue by brimob-sowax** [MsLolita/grass#86]
Traceback (most recent call last):
  File "/root/grass/main.py", line 7, in <module>
    from asyncio import WindowsSelectorEventLoopPolicy
ImportError: cannot import name 'WindowsSelectorEventLoopPolicy' from 'asyncio' (/usr/lib/python3.12/asyncio/__init__.py)

**Comment by binbin096** [comment]
if sys.platform == 'win32':
  from asyncio import WindowsSelectorEventLoopPolicy

**Comment by binbin096** [comment]
if sys.platform == 'win32':
  from asyncio import WindowsSelectorEventLoopPolicy

**Comment by binbin096** [comment]
![image](https://github.com/user-attachments/assets/17bef581-7665-4c04-bba8-f1afd137a640)

**Comment by brimob-sowax** [comment]
> ![image](https://private-user-images.githubusercontent.com/59159700/389346195-17bef581-7665-4c04-bba8-f1afd137a640.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MDM2NjgsIm5iZiI6MTczMjUwMzM2OCwicGF0aCI6Ii81OTE1OTcwMC8zODkzNDYxOTUtMTdiZWY1ODEtNzY2NS00YzA0LWJiYTgtZjFhZmQxMzdhNjQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDAyNTYwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlMTJmYmJkY2M2MDI1MjRkNTdmNGE3MmYwYzI4ODJiZmFjNmIyMTVmNWJjODI3MGQ3Mzk5MTY5MTNhNzNhMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9wlnv4OQAG0XBYFZ9Qkym_q2akaekoSzAQtzTY0Aeeo)


 File "/root/grass/main.py", line 8
    from asyncio import WindowsSelectorEventLoopPolicy
    ^
IndentationError: expected an indented block after 'if' statement on line 7

**Comment by brimob-sowax** [comment]
> ![image](https://private-user-images.githubusercontent.com/59159700/389346195-17bef581-7665-4c04-bba8-f1afd137a640.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MDM5MjEsIm5iZiI6MTczMjUwMzYyMSwicGF0aCI6Ii81OTE1OTcwMC8zODkzNDYxOTUtMTdiZWY1ODEtNzY2NS00YzA0LWJiYTgtZjFhZmQxMzdhNjQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDAzMDAyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViZWRjYTE4Y2YzZDRhZmQ4MDQ0MjNjZWRkZjQ0NmJiMDVmZDY1NmM2NTA4ZWM4ZjJmNzBhNTA2MjkzYTEwYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.p6C2-mhJzaX7V6Yqyild0gaFxU9BNtsGsT6JrF9SVVk)

INFO 1 | Login retrying... Failed to perform, curl: (56) CONNECT tunnel failed, response 403. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
