### ISSUE TITLE
There was an error.

### ISSUE THREAD

**Issue by lilin998** [MsLolita/grass#92]
Constantly trying to log in again

**Comment by ZaryImortal** [comment]
only works with private proxies

**Comment by lilin998** [comment]
> 仅适用于私人代理

Your normal?

**Comment by ZaryImortal** [comment]
![image](https://github.com/user-attachments/assets/e9007985-74f0-4fa1-8268-00ff5af9a971)
https://proxy-sale.com/?partner_link=RjN9JuPcX6
coupon: RjN9JuPcX6
