### ISSUE TITLE
Вопрос

### ISSUE THREAD

**Issue by IMPER1A-V** [MsLolita/grass#95]
Возможно ли получить количество устройств через api?

**Comment by IMPER1A-V** [comment]
установил все библиотеки, программа не запускается 


C:\Users\USER\Desktop\grass-master>python interface.py

C:\Users\USER\Desktop\grass-master>pause
Для продолжения нажмите любую клавишу . . .

**Comment by IMPER1A-V** [comment]
File "C:\Users\Administrator\Desktop\grass-master\interface.py", line 7, in <module>
    from PySide6.QtWidgets import QApplication, QMainWindow, QFileDialog
ImportError: DLL load failed while importing QtWidgets: Не найдена указанная процедура.

**Comment by MsLolita** [comment]
установи модули, и запускай через python main.py
