### ISSUE TITLE
Proxy score not found! Retrying...

### ISSUE THREAD

**Issue by oyjcmyn** [MsLolita/grass#97]
Now all of them are proxy score not found! Retrying...
Changing the IP proxy is the same.

**Comment by Borntowarn** [comment]
+1

**Comment by ferbiy** [comment]
+1

i believe that's the problem of the proxy itself, but I see no way to check which are connected ok and which must be replaced

**Comment by Borntowarn** [comment]
There is no connected network on account's dashboard, so just can't score network

**Comment by Dayger666** [comment]
+1

**Comment by MsLolita** [comment]
I guess need to wait

**Comment by tiennguyen12g** [comment]
I have same issue, tool is not work . "Proxy score not found! Retrying..."

**Comment by ancoracagna** [comment]
Same issue, hope to resolve it, because I just bought a lot of proxies 🙏🏻

**Comment by Borntowarn** [comment]
Set proxy_score = 0, so skip this section. I was running script for ~2 hrs and getting 'mining' mesages, but wasn't any network/device on account's dashboard and no points added

**Comment by Borntowarn** [comment]
> I guess need to wait

Set proxy_score = 0, so skip this section. I was running script for ~2 hrs and getting 'mining' mesages, but wasn't any network/device on account's dashboard and no points added

**Comment by Borntowarn** [comment]
> Whatever backend grass has might just take time to do everything. Points can even take up to 48 hours to be properly reflected (According to discord).
> 
> The wait time between each score check might need to be significantly longer, or alternatively, the score could be monitored continuously in the background while connected, with a disconnection triggered if it falls below the minimum threshold. I believe eventually EVERY device that has successfully connected will have its score updated in the backend( even if 0) as long as they are connected(sending pings and getting pongs). It could take hours but eventually the score check will return a score.

Even if node getting pong request, for some reason it isn't displayed on account network page, so I think we can't get points without any connected device

**Comment by Borntowarn** [comment]
Script can't get proxy score due to the lack of connected devices. I'll try to run longer session without proxy checking

**Comment by ka1oda** [comment]
Does anyone have any new information?

**Comment by ancoracagna** [comment]
> Does anyone have any new information?

Change MIN_PROXY_SCORE in config.py to 0 to skip proxy score checking and it will work correctly

**Comment by milkthecow-moo** [comment]
> > Whatever backend grass has might just take time to do everything. Points can even take up to 48 hours to be properly reflected (According to discord).
> > The wait time between each score check might need to be significantly longer, or alternatively, the score could be monitored continuously in the background while connected, with a disconnection triggered if it falls below the minimum threshold. I believe eventually EVERY device that has successfully connected will have its score updated in the backend( even if 0) as long as they are connected(sending pings and getting pongs). It could take hours but eventually the score check will return a score.
> 
> Even if node getting pong request, for some reason it isn't displayed on account network page, so I think we can't get points without any connected device

you may be onto somthing .I  revisited the extension and saw that {"jwt":{"action":"getCurrentVersion"},"action":"VALIDATE_JWT"} is sent after auth. Not sure if this makes a difference.  Is it possible devices aren't being correctly registered?

**Comment by Borntowarn** [comment]
Is anyone able to run this correctly?

**Comment by hdmjdp** [comment]
> somthing

got nothing

**Comment by YiMoWanXia** [comment]
Are you responding with error: 404?

**Comment by FiNT222** [comment]
> Я думаю, нужно подождать
К сожалению пока ничего не заработало. При этом через приложение в браузере поинты фармятся и отображаются в дашборде.

**Comment by beck-8** [comment]
I only have one that keeps doing this, which is the third piece of data. After I changed the IP, it still prompts that there is a problem with the third proxy. Then I switched to an agent that already had an account.

**Comment by Quincy-seun** [comment]
> I only have one that keeps doing this, which is the third piece of data. After I changed the IP, it still prompts that there is a problem with the third proxy. Then he switched to an agent that already had an account.
> 
> ![image](https://private-user-images.githubusercontent.com/34204218/395810937-84469173-7a9b-4324-91aa-7cc4702eee52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyMDc0MzcsIm5iZiI6MTczNDIwNzEzNywicGF0aCI6Ii8zNDIwNDIxOC8zOTU4MTA5MzctODQ0NjkxNzMtN2E5Yi00MzI0LTkxYWEtN2NjNDcwMmVlZTUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE0VDIwMTIxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlMzJjNTEwYjFkMzcwY2E2NmY4NzhiMTA3OGEwYzgxNWM5MzE0MGU4MzUyYTdhNDhjYWY0ZWE5M2IxNjg3NjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XU-eIyZnl8wNKYDqJ5SsR4MC6xEhUQ3-vGVmaug4QyY)

How do you get it to mine points? Mine only shows this
![image](https://github.com/user-attachments/assets/cbf3d8c5-38e7-4179-8b1e-1e63d4f42833)

**Comment by beck-8** [comment]
@Quincy-seun  check your network

**Comment by APX403** [comment]
same problem, even with proxy score set to 0 in the config

**Comment by MsLolita** [comment]
пофиксил дней 5 назад

**Comment by MsLolita** [comment]
> > I only have one that keeps doing this, which is the third piece of data. After I changed the IP, it still prompts that there is a problem with the third proxy. Then he switched to an agent that already had an account.
> > ![image](https://private-user-images.githubusercontent.com/34204218/395810937-84469173-7a9b-4324-91aa-7cc4702eee52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyMDc0MzcsIm5iZiI6MTczNDIwNzEzNywicGF0aCI6Ii8zNDIwNDIxOC8zOTU4MTA5MzctODQ0NjkxNzMtN2E5Yi00MzI0LTkxYWEtN2NjNDcwMmVlZTUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE0VDIwMTIxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlMzJjNTEwYjFkMzcwY2E2NmY4NzhiMTA3OGEwYzgxNWM5MzE0MGU4MzUyYTdhNDhjYWY0ZWE5M2IxNjg3NjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XU-eIyZnl8wNKYDqJ5SsR4MC6xEhUQ3-vGVmaug4QyY)
> 
> How do you get it to mine points? Mine only shows this ![image](https://private-user-images.githubusercontent.com/114014049/395816194-cbf3d8c5-38e7-4179-8b1e-1e63d4f42833.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyNzc2NjIsIm5iZiI6MTczNDI3NzM2MiwicGF0aCI6Ii8xMTQwMTQwNDkvMzk1ODE2MTk0LWNiZjNkOGM1LTM4ZTctNDE3OS04YjFlLTFlNjNkNGY0MjgzMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNVQxNTQyNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YmI1ZjAyMDY0YTc3NWQwMDNkOTI3YzJmMmJjZGY2YjZmZmYzNWQ2MzEzOGY0OTMzMmI5YjdiM2ZmMDU4YjIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Q5wgbPquP-YbxPtyz-x6vU1ONwzfp2Z1Xo-In9BnZuw)

proxy issue, choose gemups.com

**Comment by Bekloppten** [comment]
that u prefer gemups confuses me. which proxy config u used at gemups ? i used different config settings, never had such a bad performance. even some free proxies gave me more points. most of  gemups proxies, i used, where shown in grass dashboard with 0 minutes connection time and zero points for days. tried to talk to the support, but they didnt gave any support.
